# Generated by Django 2.2.14 on 2020-11-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20201123_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='imagen',
        ),
    ]
