# Generated by Django 2.2.14 on 2020-11-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('edad', models.IntegerField(null=True)),
                ('activo', models.BooleanField(null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase')),
            ],
        ),
    ]
