# Generated by Django 2.2.14 on 2020-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='clase',
        ),
        migrations.AddField(
            model_name='alumno',
            name='clases',
            field=models.ManyToManyField(null=True, related_name='estudiantes', to='clases.Clase'),
        ),
    ]
