# Generated by Django 2.2.14 on 2020-11-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20201123_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='clases',
            field=models.ManyToManyField(related_name='estudiantes', to='clases.Clase'),
        ),
    ]
