# Generated by Django 2.2.14 on 2020-11-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20201123_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
